Repository KI-labs/kaos, pull requests merged in 2019-10, with the labels that each got.

#52 #51 - bug fix for (accidentally) removed config file
  cli/kaos_cli/utils/decorators.py
Labels: hacktoberfest

#49 k-20: Multiple cloud build on the same directory
  cli/kaos_cli/commands/build.py
  cli/kaos_cli/constants.py
  cli/kaos_cli/facades/backend_facade.py
  cli/kaos_cli/factories/simple_factory.py
  cli/kaos_cli/services/state_service.py
  cli/kaos_cli/services/terraform_service.py
  cli/kaos_cli/utils/decorators.py
  cli/kaos_cli/utils/validators.py
Labels: hacktoberfest

#55 #54 - adapted links
  README.md
Labels: bug

#59 Check Local Port Collision [Feature] (#28)
  .gitignore
  Pipfile.lock
  cli/kaos_cli/commands/build.py
  cli/kaos_cli/utils/tests/test_validation.py
  cli/kaos_cli/utils/validators.py
Labels: feature

#63 #62 - fix tf_service
  cli/kaos_cli/facades/backend_facade.py
Labels: bug
